# Generated by Django 3.0.5 on 2020-05-06 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("csv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DATA_EXPORT_PENDING", "data_export_pending"),
                            ("DATA_EXPORT_SUCCESS", "data_export_success"),
                            ("DATA_EXPORT_FAILED", "data_export_failed"),
                            ("DATA_EXPORT_DELETED", "data_export_deleted"),
                            ("EXPORTED_FILE_SENT", "exported_file_sent"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "export_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="csv.ExportFile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_csv_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
